services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - my_network
    depends_on:
      - shaw-family
    restart: always

  shaw-family:
    image: shaw-familly
    container_name: shaw-family
    build:
      context: ./shaw-family
    networks:
      - my_network
    expose:
      - "3000"
    restart: always

networks:
  my_network:
    driver: bridge
