services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certificates:/etc/letsencrypt
      - ./nginx/logs:/var/log/nginx
    networks:
      - my_network
    depends_on:
      - shaw-family
    restart: always

  shaw-family:
    image: shaw-familly
    container_name: shaw-family
    build:
      context: ./shaw-family
    networks:
      - my_network
    expose:
      - "3000"
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certificates:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./var/lib/letsencrypt:/var/lib/letsencrypt
      - ./var/log/letsencrypt:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
